config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'tasks#index'

  # CREATE add at task
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  # READ all tasks
  get 'tasks', to: 'tasks#index'

  # READ one task details
  get 'tasks/:id', to: 'tasks#show', as: :task # still don't quite understand the as: re_named url?

  # UPDATE
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task# takes to your form edit page
  patch 'tasks/:id', to: 'tasks#update'

  # DELETE
  delete 'tasks/:id', to: 'tasks#destroy'
end


# need to add an edit and destroy icon that redirects to corresponding pages

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :details, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path(@task)
  end

  private

  def task_params
    # only look into the task key and permit only title, details and competed fields.
    params.require(:task).permit(:title, :details, :completed)
  end

  def find_task
    @task = Task.find(params[:id])
  end
end

# params store the id from the url in a hash as the key id:
# 1:44:20

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= link_to 'Tasks list', root_path %>
<%= form_for @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit%>
<% end %>

app/views/tasks/edit.html.erb
<h1><%= @task.title %></h1>
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>
<%= link_to 'Create a new task', tasks_new_path %>
<ul>
  <% @tasks.each do |task| %>
  <li><%= link_to task.title, task_path(task) %></li>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<h1>Create a new task</h1>
<%= render 'form' %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<%= link_to 'Tasks list', root_path %>
<%= link_to 'Edit', edit_task_path(@task)%>
<%= link_to 'Delete', task_path(@task), method: :delete, data: { confirm: 'Are you sure you want to delete?'} %>
<p><%= @task.details%></p>

<!-- timestamp 1:33:40 -->